/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("interviewpractice.kotlin-library-conventions")
}

dependencies {
    testImplementation(kotlin("test"))
    testImplementation(kotlin("test-junit"))
}